<a href="https://colab.research.google.com/github/odhiambocalvins200-cloud/Data-Cleaning-and-Visualization/blob/main/Pandas_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to pandas
Series = A one dimensional array - any type of data, int,str,bol Dataframe

In [ ]:
#importing the library
import pandas as pd

In [ ]:
data = {
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'city':['New York','San Francisco','Los Angeles'],
    'salary':[50000, 60000, 70000]
}
#data_for_numpy = np.array([1,2,3])
df = pd.DataFrame(data)
print(df)

      Name  Age           city  salary
0    Alice   25       New York   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000

In [ ]:
#peak into the first two rows
df.head(2)

    Name  Age           city  salary
0  Alice   25       New York   50000
1    Bob   30  San Francisco   60000

In [ ]:
df.tail(2)

      Name  Age           city  salary
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000

In [ ]:
df.shape

(3, 4)

In [ ]:
df.columns

Index(['Name', 'Age', 'city', 'salary'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   city    3 non-null      object
 3   salary  3 non-null      int64
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

        Age   salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0

In [ ]:
df.sample(2)

      Name  Age           city  salary
2  Charlie   35    Los Angeles   70000
1      Bob   30  San Francisco   60000

In [ ]:
df[['Name' , 'Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df.isnull().sum()

Name      0
Age       0
city      0
salary    0
dtype: int64

In [ ]:
#dealing with missing values
df.dropna()#drop
df.fillna(25)#fill
df['Age'].fillna(df['Age'].mean(),inplace=True)

In [ ]:
df[df['Age'] > 30]

      Name  Age         city  salary
2  Charlie   35  Los Angeles   70000

In [ ]:
df.sort_values('Age' , ascending=False)

      Name  Age           city  salary
2  Charlie   35    Los Angeles   70000
1      Bob   30  San Francisco   60000
0    Alice   25       New York   50000

In [ ]:
print('Hello Jupyter')

Hello Jupyter

In [ ]:
x = 22
print(x)

22

In [ ]:
type(x)

int

In [ ]:
x,y,z ='boy', 'girl', 'adult'
print(x)
print(y)
print(z)

boy
girl
adult

In [ ]:
x=y=z='boy'
print(x)
print(y)
print(z)

boy
boy
boy

In [ ]:
ice_cream = ['chocolate', 'vanilla', 'strawberry']
x,y,z = ice_cream
print(x)
print(y)
print(z)

chocolate
vanilla
strawberry

In [ ]:
'single quote'

'single quote'

In [ ]:
"double quote"

'double quote'

In [ ]:
Multiline = """ThIS IS MY HOME
I LOVE MY HOME"""
print(Multiline)

ThIS IS MY HOME
I LOVE MY HOME

In [ ]:
a = 'HELLO WORLD'
print(a[3:-5])

LO

In [ ]:
tuple_stoops = (1,5,8,6)
type(tuple_stoops)

tuple

In [ ]:
 daily_wifes_print_log = (1,2,6,7,18,20)

In [ ]:
if 25 > 10:
  print('t'  )

t

In [ ]:
ice_cream = {'chocolate': 'alex', 'vanilla':'big'}
for key, value in ice_cream.items():
  print(key,value)
#

chocolate alex
vanilla big

In [ ]:
flavors = ['chocolate', 'vanilla', 'strawberry']
toppings = ['sprinkles', 'coconuts', 'cherry']

In [ ]:
for one in flavors:
  for two in toppings:
    print(one, 'topped with',two)

chocolate topped with sprinkles
chocolate topped with coconuts
chocolate topped with cherry
vanilla topped with sprinkles
vanilla topped with coconuts
vanilla topped with cherry
strawberry topped with sprinkles
strawberry topped with coconuts
strawberry topped with cherry

In [ ]:
number = 0
while number < 5:
  print(number)
  number = number + 1

0
1
2
3
4

In [ ]:
weight = int(input("Enter your weight in pounds: "))
height = int(input("Enter your height in inches:"))
BMI = (weight * 703) / (height * height)
print(BMI)

Enter your weight in pounds: 12
Enter your height in inches:30
9.373333333333333